version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - ls -la *
      - chmod +x ./gradlew
      - ./gradlew clean
      #- ./gradlew assembleAndroidTest
      - ./gradlew assembleDebug
      - ls -la ./app/build/outputs/apk/debug/
artifacts:
  files:
    - './app/build/outputs/**/*.apk'
  discard-paths: yes